### ISSUE TITLE
Build error critical

### ISSUE THREAD

**Issue by nathaneltitane** [leozide/leocad#755]
**Describe the bug**
Cannot build leocad under ubuntu 21.04 arm 64

**To Reproduce**
1. use leocad linux build instructions
2. attempt to build continious github code
3. get error
--
In file included from common/light.cpp:3:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
In file included from common/minifig.cpp:3:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
In file included from common/lc_context.h:5,
                 from common/lc_library.h:3,
                 from common/lc_application.cpp:4:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
In file included from common/lc_context.h:5,
                 from common/texfont.cpp:4:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
In file included from common/piece.cpp:3:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
In file included from common/lc_context.h:5,
                 from common/lc_view.h:3,
                 from common/project.cpp:11:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
In file included from common/pieceinf.cpp:5:
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’:
common/lc_colors.h:61:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromExtendedColor(int)’ not a return-statement
   61 | }
      | ^
common/lc_colors.h: In function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’:
common/lc_colors.h:67:1: error: body of ‘constexpr’ function ‘constexpr quint32 lcGetColorCodeFromOriginalColor(int)’ not a return-statement
   67 | }
      | ^
make: *** [Makefile:1330: build/release/.obj/light.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:1221: build/release/.obj/texfont.o] Error 1
make: *** [Makefile:1318: build/release/.obj/minifig.o] Error 1
make: *** [Makefile:1293: build/release/.obj/piece.o] Error 1
make: *** [Makefile:1355: build/release/.obj/lc_application.o] Error 1
make: *** [Makefile:1273: build/release/.obj/pieceinf.o] Error 1
make: *** [Makefile:1250: build/release/.obj/project.o] Error 1
--

**Expected behavior**
build instructions should help build binary successfully

**Screenshots**

**Version (please complete the following information):**
 - OS: linux ubuntu 21.04 arm64
 - LeoCAD Version - continuous

**Crash information:**
Some versions of LeoCAD will show a message that they saved a minidump file when they crash, if you see this message please attach the file.

**Additional context**
Add any other context about the problem here. If you're seeing a graphical issue, adding a screenshot of the About Dialog may help.

**Comment by nathaneltitane** [comment]
builds fine on 21.10...

**Comment by leozide** [comment]
Should be fixed
