### ISSUE TITLE
Qt 5.4 incompatibility

### ISSUE THREAD

**Issue by trevorsandy** [leozide/leocad#721]
**Describe the bug**

This QLatin1String constructor was introduced in Qt 5.6; thus, is not compatible with the declaration that LeoCAD requires Qt 5.4 or greater. A build break will result from attempts to build on Qt 5.5.1 for example.

https://github.com/leozide/leocad/blob/763fe50131e5d9ace89c7919b64d2107540aa2eb/common/lc_library.cpp#L341

**To Reproduce**
Trigger a build on Ubuntu Xenial with default Qt 5.5.1

**Expected behavior**
Successful build

**Screenshots**
N/A

**Version (please complete the following information):**
 - OS: Ubuntu Xenial/Qt 5.5.1 aarch64
 - LeoCAD Version: Continuous

**Crash information:**
```
common/lc_library.cpp: In member function void lcPiecesLibrary::UpdateStudStyleSource():
common/lc_library.cpp:357:17: error: no matching function for call to QLatin1String::QLatin1String()
   QLatin1String(),                                  // Plain
                 ^
In file included from /usr/include/aarch64-linux-gnu/qt5/QtCore/qobject.h:41:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtWidgets/qwidget.h:38,
                 from /usr/include/aarch64-linux-gnu/qt5/QtWidgets/QWidget:1,
                 from common/lc_global.h:7:
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:87:21: note: candidate: QLatin1String::QLatin1String(const QByteArray&)
     inline explicit QLatin1String(const QByteArray &s) : m_size(int(qstrnlen(s.constData(), s.size()))), m_data(s.constData()) {}
                     ^
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:87:21: note:   candidate expects 1 argument, 0 provided
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:86:38: note: candidate: constexpr QLatin1String::QLatin1String(const char*, int)
     Q_DECL_CONSTEXPR inline explicit QLatin1String(const char *s, int sz) : m_size(sz), m_data(s) {}
                                      ^
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:86:38: note:   candidate expects 2 arguments, 0 provided
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:85:38: note: candidate: constexpr QLatin1String::QLatin1String(const char*)
     Q_DECL_CONSTEXPR inline explicit QLatin1String(const char *s) : m_size(s ? int(strlen(s)) : 0), m_data(s) {}
                                      ^
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:85:38: note:   candidate expects 1 argument, 0 provided
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:82:7: note: candidate: constexpr QLatin1String::QLatin1String(const QLatin1String&)
 class QLatin1String
       ^
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:82:7: note:   candidate expects 1 argument, 0 provided
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:82:7: note: candidate: constexpr QLatin1String::QLatin1String(QLatin1String&&)
/usr/include/aarch64-linux-gnu/qt5/QtCore/qstring.h:82:7: note:   candidate expects 1 argument, 0 provided
common/lc_global.h:36:34: error: static assertion failed: FileNames size mismatch.
 #define LC_ARRAY_SIZE_CHECK(a,s) static_assert(LC_ARRAY_COUNT(a) == static_cast<int>(s), QT_STRINGIFY(a) " size mismatch.")
                                  ^
common/lc_library.cpp:367:2: note: in expansion of macro LC_ARRAY_SIZE_CHECK
  LC_ARRAY_SIZE_CHECK(FileNames, lcStudStyle::Count);
  ^
In file included from common/lc_context.h:3:0,
                 from common/lc_library.h:3,
                 from common/lc_library.cpp:2:
```

**Additional context**
Correcting this behaviour is trivial. 
You can use a single constructor declaration initialised with 0:
 ```
QLatin1String(0);
```
or conditional directives:
```
#if (QT_VERSION >= QT_VERSION_CHECK(5, 6, 0))
QLatin1String();
#elif (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
QLatin1String(0);
#endif
```

See: [QLatin1String()](https://doc.qt.io/qt-5/qlatin1string.html#QLatin1String)

Cheers,

**Comment by rsbx** [comment]
My Debian 10 (Buster) amd64 system has Qt 5.11 and LeoCAD builds without 
warnings or errors.
